# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-28 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('distance', models.CharField(default='', max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='events_images')),
            ],
        ),
    ]
