# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-31 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='month',
            field=models.CharField(default='', max_length=254),
        ),
    ]
