# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-02 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Month',
        ),
    ]
