# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-31 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200331_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='region',
            field=models.CharField(default='', max_length=254),
        ),
    ]
