# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-31 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='distance_range',
            field=models.CharField(default='', max_length=254),
        ),
    ]
