# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-01 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
