# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-01 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200301_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='month',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='events.Month'),
        ),
    ]
