# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-21 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_auto_20200421_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShoeSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Size',
        ),
        migrations.AddField(
            model_name='product',
            name='clothes_size',
            field=models.ForeignKey(default=36, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='clothessize', to='discounts.ClothesSize'),
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_size',
            field=models.ForeignKey(default=36, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='shoesize', to='discounts.ShoeSize'),
        ),
    ]
