# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-10 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_auto_20200210_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='description_first',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_introduction',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_second',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_third',
            field=models.TextField(null=True),
        ),
    ]
