# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-26 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_remove_size_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='discounts.Size'),
        ),
    ]
