# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-14 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0003_auto_20200312_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
