# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-10 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_auto_20200210_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='normal_price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
