# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-10 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0005_product_normal_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_third',
            field=models.TextField(blank=True, null=True),
        ),
    ]
