# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-26 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0005_auto_20200421_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shoe_size',
        ),
        migrations.AddField(
            model_name='product',
            name='shoe_size',
            field=models.ManyToManyField(blank=True, null=True, related_name='shoesize', to='discounts.ShoeSize'),
        ),
    ]
