# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-06 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0005_auto_20200406_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.Product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discounts.Size')),
            ],
        ),
    ]
