# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-26 14:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0006_auto_20200426_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='clothes_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='discounts.ClothesSize'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shoe_size',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='discounts.ShoeSize'),
        ),
    ]
