# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-17 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0006_auto_20200317_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description_first',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_introduction',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_second',
        ),
        migrations.RemoveField(
            model_name='product',
            name='description_third',
        ),
    ]
