# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-26 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0007_auto_20200426_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='clothes_size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='shoe_size',
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
