# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-19 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0008_auto_20200319_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('xxs', 'XX-Small'), ('xs', 'X-Small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'X-Large'), ('xxl', 'XX-Large'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47')], default='n/a', max_length=3),
        ),
    ]
