# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-29 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0010_auto_20200428_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='discounts.Product'),
        ),
    ]
