# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-07 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0011_auto_20200429_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('watches', 'watches'), ('clothes', 'clothes'), ('shoes', 'shoes'), ('events', 'events')], default='shoes', max_length=15),
        ),
    ]
