# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-07 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0012_auto_20200507_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='size',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
