# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-07 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0013_auto_20200507_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='more_info',
            field=models.TextField(null=True),
        ),
    ]
