# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-07 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200207_1809'),
        ('community', '0002_auto_20200207_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.UserProfile', to_field='image'),
        ),
    ]
