# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-07 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200207_1836'),
        ('community', '0003_post_author_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_image',
        ),
        migrations.AddField(
            model_name='post',
            name='author_first_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.UserProfile', to_field='first_name'),
        ),
    ]
