# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-08 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200208_1450'),
        ('community', '0004_auto_20200207_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_first_name',
        ),
        migrations.AddField(
            model_name='post',
            name='author_image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='accounts.UserProfile', to_field='image'),
        ),
    ]
