# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-20 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profilepost_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepost',
            old_name='user',
            new_name='profile_post_user',
        ),
    ]
