# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-06 14:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200306_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
