# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-12 18:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200512_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactuser',
            old_name='title',
            new_name='subject',
        ),
    ]
