# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-20 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contactuser_more_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactuser',
            name='more_content',
        ),
    ]
