# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-01 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200201_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('optional', 'does it mattter?'), ('male', 'male'), ('female', 'female')], default='optional', max_length=10),
        ),
    ]
