# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-20 15:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_remove_contactuser_more_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuser',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
