# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-02-20 14:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_auto_20200220_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilepost',
            name='profile_post_user',
        ),
        migrations.AddField(
            model_name='profilepost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
