# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-17 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200512_1906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactuser',
            name='recipient',
        ),
    ]
