# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-12 10:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_contactuser_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactuser',
            name='receiver',
        ),
        migrations.AddField(
            model_name='contactuser',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
