# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-12 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200512_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactuser',
            old_name='published_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='contactuser',
            old_name='content',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contactuser',
            old_name='title',
            new_name='subject',
        ),
    ]
