# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-12 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200307_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='about_me',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
