# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-20 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_contactuser_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactuser',
            name='recipient',
            field=models.CharField(max_length=200),
        ),
    ]
