# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-20 12:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200520_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactuser',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='recipient', to=settings.AUTH_USER_MODEL),
        ),
    ]
