# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-31 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=99, null=True),
        ),
    ]
