# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-06-01 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200601_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='email',
            new_name='repeat_email',
        ),
    ]
