# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-04-03 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='size',
        ),
    ]
