# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-04 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0005_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ad_one',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='ad_two',
            field=models.TextField(blank=True, null=True),
        ),
    ]
