# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-04 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0006_auto_20200504_1101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='ad_one',
            new_name='ad_one_contact',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='ad_two',
            new_name='ad_one_content',
        ),
        migrations.AddField(
            model_name='article',
            name='ad_one_image',
            field=models.ImageField(blank=True, null=True, upload_to='inspiration_images'),
        ),
        migrations.AddField(
            model_name='article',
            name='ad_one_introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
